'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_PL
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_PL", GetType(Resource_PL).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PL.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Całkowicie się zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property a1() As String
            Get
                Return ResourceManager.GetString("a1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raczej się zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property a2() As String
            Get
                Return ResourceManager.GetString("a2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raczej się NIE zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property a3() As String
            Get
                Return ResourceManager.GetString("a3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Całkowicie się NIE zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property a4() As String
            Get
                Return ResourceManager.GetString("a4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property aNie() As String
            Get
                Return ResourceManager.GetString("aNie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zgadzam.
        '''</summary>
        Friend Shared ReadOnly Property aTak() As String
            Get
                Return ResourceManager.GetString("aTak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czy chcesz wysłać wynik jako email?.
        '''</summary>
        Friend Shared ReadOnly Property msgAskEmail() As String
            Get
                Return ResourceManager.GetString("msgAskEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie odpowiedziałeś na wszystkie pytania - sprawdź pytania z oznaczone na czerwono.
        '''</summary>
        Friend Shared ReadOnly Property msgBrakAnswer() As String
            Get
                Return ResourceManager.GetString("msgBrakAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mój wynik w teście AQ.
        '''</summary>
        Friend Shared ReadOnly Property msgEmailSubject() As String
            Get
                Return ResourceManager.GetString("msgEmailSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Psycholog Simon Baron-Cohen i jego współpracownicy z Ośrodka Badań nad Autyzmem w Cambridge stworzyli test AQ, określający współczynnik cech autystycznych u dorosłych. Testu tego nie należy jednak traktować jako diagnozy.
        '''.
        '''</summary>
        Friend Shared ReadOnly Property msgInfo() As String
            Get
                Return ResourceManager.GetString("msgInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wolę robić rzeczy w grupie, niż samemu.
        '''</summary>
        Friend Shared ReadOnly Property q1() As String
            Get
                Return ResourceManager.GetString("q1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie mam kłopotów ze śledzeniem rozmowy prowadzonej przez kilka osób w grupie..
        '''</summary>
        Friend Shared ReadOnly Property q10() As String
            Get
                Return ResourceManager.GetString("q10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spotkania towarzyskie nie stanowią dla mnie problemu..
        '''</summary>
        Friend Shared ReadOnly Property q11() As String
            Get
                Return ResourceManager.GetString("q11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zauważam szczegóły niewidoczne dla innych..
        '''</summary>
        Friend Shared ReadOnly Property q12() As String
            Get
                Return ResourceManager.GetString("q12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wolę pójść do biblioteki niż na imprezę..
        '''</summary>
        Friend Shared ReadOnly Property q13() As String
            Get
                Return ResourceManager.GetString("q13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie mam problemów z wymyślaniem historyjek..
        '''</summary>
        Friend Shared ReadOnly Property q14() As String
            Get
                Return ResourceManager.GetString("q14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bardziej przywiązuję się do osób niż do przedmiotów..
        '''</summary>
        Friend Shared ReadOnly Property q15() As String
            Get
                Return ResourceManager.GetString("q15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moje zainteresowania bardzo mnie angażują, irytuję się jak nie mogę się nim zajmować..
        '''</summary>
        Friend Shared ReadOnly Property q16() As String
            Get
                Return ResourceManager.GetString("q16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię pogaduszki o niczym, np. w windzie..
        '''</summary>
        Friend Shared ReadOnly Property q17() As String
            Get
                Return ResourceManager.GetString("q17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kiedy coś mówię, często nie dopuszczam innych do głosu..
        '''</summary>
        Friend Shared ReadOnly Property q18() As String
            Get
                Return ResourceManager.GetString("q18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fascynują mnie liczby..
        '''</summary>
        Friend Shared ReadOnly Property q19() As String
            Get
                Return ResourceManager.GetString("q19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wolę wykonywać czynności stale w ten sam sposób..
        '''</summary>
        Friend Shared ReadOnly Property q2() As String
            Get
                Return ResourceManager.GetString("q2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kiedy czytam książkę, mam kłopot ze zrozumieniem intencji postaci..
        '''</summary>
        Friend Shared ReadOnly Property q20() As String
            Get
                Return ResourceManager.GetString("q20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czytanie beletrystyki nie sprawia mi przyjemności.
        '''</summary>
        Friend Shared ReadOnly Property q21() As String
            Get
                Return ResourceManager.GetString("q21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mam kłopot z nawiązywaniem znajomości..
        '''</summary>
        Friend Shared ReadOnly Property q22() As String
            Get
                Return ResourceManager.GetString("q22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zauważam wzorce (szablony) w zdarzeniach..
        '''</summary>
        Friend Shared ReadOnly Property q23() As String
            Get
                Return ResourceManager.GetString("q23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wolę pójść do teatru niż do muzeum..
        '''</summary>
        Friend Shared ReadOnly Property q24() As String
            Get
                Return ResourceManager.GetString("q24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie denerwuję się, gdy mój rytm dnia jest w jakiś sposób zakłócony..
        '''</summary>
        Friend Shared ReadOnly Property q25() As String
            Get
                Return ResourceManager.GetString("q25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Często łapię się na tym, że nie wiem, jak podtrzymać rozmowę.
        '''</summary>
        Friend Shared ReadOnly Property q26() As String
            Get
                Return ResourceManager.GetString("q26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie mam problemów z „czytaniem między wierszami”, gdy ktoś coś do mnie mówi..
        '''</summary>
        Friend Shared ReadOnly Property q27() As String
            Get
                Return ResourceManager.GetString("q27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bardziej koncentruję się na całości, niż na szczegółach..
        '''</summary>
        Friend Shared ReadOnly Property q28() As String
            Get
                Return ResourceManager.GetString("q28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mam problem z zapamiętywaniem numerów telefonów..
        '''</summary>
        Friend Shared ReadOnly Property q29() As String
            Get
                Return ResourceManager.GetString("q29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jeżeli próbuję sobie coś wyobrazić, nie sprawia mi problemu utworzenie obrazu w myślach..
        '''</summary>
        Friend Shared ReadOnly Property q3() As String
            Get
                Return ResourceManager.GetString("q3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zazwyczaj nie zauważam drobnych zmian w sytuacji lub wyglądzie osób..
        '''</summary>
        Friend Shared ReadOnly Property q30() As String
            Get
                Return ResourceManager.GetString("q30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zauważam, kiedy to co mówię zaczyna innych nudzić..
        '''</summary>
        Friend Shared ReadOnly Property q31() As String
            Get
                Return ResourceManager.GetString("q31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie mam problemu z tym, by równocześnie wykonywać więcej niż jedno zadanie.
        '''</summary>
        Friend Shared ReadOnly Property q32() As String
            Get
                Return ResourceManager.GetString("q32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kiedy rozmawiam przez telefon, nie mam pewności kiedy jest „moja kolej”..
        '''</summary>
        Friend Shared ReadOnly Property q33() As String
            Get
                Return ResourceManager.GetString("q33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię działać spontanicznie..
        '''</summary>
        Friend Shared ReadOnly Property q34() As String
            Get
                Return ResourceManager.GetString("q34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Często jestem ostatnią osobą, która rozumie puentę żartu.
        '''</summary>
        Friend Shared ReadOnly Property q35() As String
            Get
                Return ResourceManager.GetString("q35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Z łatwością odgaduję, co jakaś osoba myśli lub czuje na podstawie wyrazu jej twarzy..
        '''</summary>
        Friend Shared ReadOnly Property q36() As String
            Get
                Return ResourceManager.GetString("q36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jeżeli z jakiegoś powodu muszę przerwać to co robię, potrafię szybko wrócić do poprzedniej czynności..
        '''</summary>
        Friend Shared ReadOnly Property q37() As String
            Get
                Return ResourceManager.GetString("q37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jestem dobry/a w pogawędkach..
        '''</summary>
        Friend Shared ReadOnly Property q38() As String
            Get
                Return ResourceManager.GetString("q38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ludzie często zwracają mi uwagę, że mówię ciągle na ten sam temat..
        '''</summary>
        Friend Shared ReadOnly Property q39() As String
            Get
                Return ResourceManager.GetString("q39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Często bywam tak zaabsorbowany/a jednym tematem, że nie zauważam niczego więcej..
        '''</summary>
        Friend Shared ReadOnly Property q4() As String
            Get
                Return ResourceManager.GetString("q4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jako dziecko podobały mi się zabawy w udawanie, że jestem kimś innym..
        '''</summary>
        Friend Shared ReadOnly Property q40() As String
            Get
                Return ResourceManager.GetString("q40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię zbierać informacje na temat rożnych kategorii przedmiotów (np. gatunków ptaków,
        '''marek samochodów)..
        '''</summary>
        Friend Shared ReadOnly Property q41() As String
            Get
                Return ResourceManager.GetString("q41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mam kłopoty z wyobrażeniem sobie siebie w innej roli, jako kogoś innego..
        '''</summary>
        Friend Shared ReadOnly Property q42() As String
            Get
                Return ResourceManager.GetString("q42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię starannie planować każde działanie, w którym mam wziąć udział..
        '''</summary>
        Friend Shared ReadOnly Property q43() As String
            Get
                Return ResourceManager.GetString("q43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię spotkania towarzyskie..
        '''</summary>
        Friend Shared ReadOnly Property q44() As String
            Get
                Return ResourceManager.GetString("q44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mam trudności w rozpoznawaniu intencji innych ludzi..
        '''</summary>
        Friend Shared ReadOnly Property q45() As String
            Get
                Return ResourceManager.GetString("q45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nowe sytuacje powodują u mnie lęk..
        '''</summary>
        Friend Shared ReadOnly Property q46() As String
            Get
                Return ResourceManager.GetString("q46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lubię poznawać nowych ludzi..
        '''</summary>
        Friend Shared ReadOnly Property q47() As String
            Get
                Return ResourceManager.GetString("q47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jestem dobrym dyplomatą..
        '''</summary>
        Friend Shared ReadOnly Property q48() As String
            Get
                Return ResourceManager.GetString("q48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mam trudności w zapamiętywaniu dat urodzin znajomych..
        '''</summary>
        Friend Shared ReadOnly Property q49() As String
            Get
                Return ResourceManager.GetString("q49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Często słyszę ciche odgłosy, niesłyszalne dla innych..
        '''</summary>
        Friend Shared ReadOnly Property q5() As String
            Get
                Return ResourceManager.GetString("q5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Łatwo mi przychodzi bawienie się z dziećmi, gdy muszę coś lub kogoś udawać..
        '''</summary>
        Friend Shared ReadOnly Property q50() As String
            Get
                Return ResourceManager.GetString("q50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zazwyczaj zapamiętuję drobne informacje, np. numery rejestracyjne samochodów..
        '''</summary>
        Friend Shared ReadOnly Property q6() As String
            Get
                Return ResourceManager.GetString("q6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Często zdarza się, że ludzie zwracają mi uwagę, że to co właśnie powiedziałem/am jest
        '''niegrzeczne, choć ja nie mam takiego wrażenia..
        '''</summary>
        Friend Shared ReadOnly Property q7() As String
            Get
                Return ResourceManager.GetString("q7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gdy czytam książkę, łatwo potrafię sobie wyobrazić, jak wyglądają bohaterowie..
        '''</summary>
        Friend Shared ReadOnly Property q8() As String
            Get
                Return ResourceManager.GetString("q8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fascynują mnie daty..
        '''</summary>
        Friend Shared ReadOnly Property q9() As String
            Get
                Return ResourceManager.GetString("q9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to możliwe że jesteś autystykiem - skonsultuj się z lekarzem.
        '''</summary>
        Friend Shared ReadOnly Property rAutism() As String
            Get
                Return ResourceManager.GetString("rAutism", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie.
        '''</summary>
        Friend Shared ReadOnly Property resDlgNo() As String
            Get
                Return ResourceManager.GetString("resDlgNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property resDlgYes() As String
            Get
                Return ResourceManager.GetString("resDlgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to punktów.
        '''</summary>
        Friend Shared ReadOnly Property rGotPoints() As String
            Get
                Return ResourceManager.GetString("rGotPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to raczej więc nie jesteś autystykiem.
        '''</summary>
        Friend Shared ReadOnly Property rSpoko() As String
            Get
                Return ResourceManager.GetString("rSpoko", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Masz.
        '''</summary>
        Friend Shared ReadOnly Property rYouGot() As String
            Get
                Return ResourceManager.GetString("rYouGot", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
