'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource_EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VBlib.Resource_EN", GetType(Resource_EN).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EN.
        '''</summary>
        Friend Shared ReadOnly Property _lang() As String
            Get
                Return ResourceManager.GetString("_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Definitely agree.
        '''</summary>
        Friend Shared ReadOnly Property a1() As String
            Get
                Return ResourceManager.GetString("a1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slightly agree.
        '''</summary>
        Friend Shared ReadOnly Property a2() As String
            Get
                Return ResourceManager.GetString("a2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Slightly disagree.
        '''</summary>
        Friend Shared ReadOnly Property a3() As String
            Get
                Return ResourceManager.GetString("a3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Definitely disagree.
        '''</summary>
        Friend Shared ReadOnly Property a4() As String
            Get
                Return ResourceManager.GetString("a4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disagree.
        '''</summary>
        Friend Shared ReadOnly Property aNie() As String
            Get
                Return ResourceManager.GetString("aNie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Agree.
        '''</summary>
        Friend Shared ReadOnly Property aTak() As String
            Get
                Return ResourceManager.GetString("aTak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to send result as email?.
        '''</summary>
        Friend Shared ReadOnly Property msgAskEmail() As String
            Get
                Return ResourceManager.GetString("msgAskEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some answers are missing, please check red colored questions.
        '''</summary>
        Friend Shared ReadOnly Property msgBrakAnswer() As String
            Get
                Return ResourceManager.GetString("msgBrakAnswer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to My result in AQ test.
        '''</summary>
        Friend Shared ReadOnly Property msgEmailSubject() As String
            Get
                Return ResourceManager.GetString("msgEmailSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Psychologist Simon Baron-Cohen and his colleagues at Cambridge’s Autism Research Centre have created the Autism-Spectrum Quotient, or AQ, as a measure of the extent of autistic traits in adults. The test is not a means for making a diagnosis, however.
        '''.
        '''</summary>
        Friend Shared ReadOnly Property msgInfo() As String
            Get
                Return ResourceManager.GetString("msgInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property msgYes() As String
            Get
                Return ResourceManager.GetString("msgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I prefer to do things with others rather than on my own..
        '''</summary>
        Friend Shared ReadOnly Property q1() As String
            Get
                Return ResourceManager.GetString("q1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In a social group, I can easily keep track of several different people’s conversations..
        '''</summary>
        Friend Shared ReadOnly Property q10() As String
            Get
                Return ResourceManager.GetString("q10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find social situations easy..
        '''</summary>
        Friend Shared ReadOnly Property q11() As String
            Get
                Return ResourceManager.GetString("q11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I tend to notice details that others do not..
        '''</summary>
        Friend Shared ReadOnly Property q12() As String
            Get
                Return ResourceManager.GetString("q12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I would rather go to a library than to a party..
        '''</summary>
        Friend Shared ReadOnly Property q13() As String
            Get
                Return ResourceManager.GetString("q13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find making up stories easy..
        '''</summary>
        Friend Shared ReadOnly Property q14() As String
            Get
                Return ResourceManager.GetString("q14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find myself drawn more strongly to people than to things..
        '''</summary>
        Friend Shared ReadOnly Property q15() As String
            Get
                Return ResourceManager.GetString("q15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I tend to have very strong interests, which I get upset about if I can’t pursue.
        '''</summary>
        Friend Shared ReadOnly Property q16() As String
            Get
                Return ResourceManager.GetString("q16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I enjoy social chitchat..
        '''</summary>
        Friend Shared ReadOnly Property q17() As String
            Get
                Return ResourceManager.GetString("q17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When I talk, it isn’t always easy for others to get a word in edgewise.
        '''</summary>
        Friend Shared ReadOnly Property q18() As String
            Get
                Return ResourceManager.GetString("q18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am fascinated by numbers.
        '''</summary>
        Friend Shared ReadOnly Property q19() As String
            Get
                Return ResourceManager.GetString("q19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I prefer to do things the same way over and over again..
        '''</summary>
        Friend Shared ReadOnly Property q2() As String
            Get
                Return ResourceManager.GetString("q2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When I’m reading a story, I find it difficult to work out the characters’ intentions..
        '''</summary>
        Friend Shared ReadOnly Property q20() As String
            Get
                Return ResourceManager.GetString("q20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I don’t particularly enjoy reading fiction..
        '''</summary>
        Friend Shared ReadOnly Property q21() As String
            Get
                Return ResourceManager.GetString("q21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it hard to make new friends..
        '''</summary>
        Friend Shared ReadOnly Property q22() As String
            Get
                Return ResourceManager.GetString("q22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I notice patterns in things all the time..
        '''</summary>
        Friend Shared ReadOnly Property q23() As String
            Get
                Return ResourceManager.GetString("q23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I would rather go to the theater than to a museum..
        '''</summary>
        Friend Shared ReadOnly Property q24() As String
            Get
                Return ResourceManager.GetString("q24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It does not upset me if my daily routine is disturbed..
        '''</summary>
        Friend Shared ReadOnly Property q25() As String
            Get
                Return ResourceManager.GetString("q25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I frequently find that I don’t know how to keep a conversation going..
        '''</summary>
        Friend Shared ReadOnly Property q26() As String
            Get
                Return ResourceManager.GetString("q26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it easy to ‘read between the lines’ when someone is talking to me..
        '''</summary>
        Friend Shared ReadOnly Property q27() As String
            Get
                Return ResourceManager.GetString("q27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I usually concentrate more on the whole picture, rather than on the small details..
        '''</summary>
        Friend Shared ReadOnly Property q28() As String
            Get
                Return ResourceManager.GetString("q28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am not very good at remembering phone numbers..
        '''</summary>
        Friend Shared ReadOnly Property q29() As String
            Get
                Return ResourceManager.GetString("q29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If I try to imagine something, I find it very easy to create a picture in my mind..
        '''</summary>
        Friend Shared ReadOnly Property q3() As String
            Get
                Return ResourceManager.GetString("q3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I don’t usually notice small changes in a situation or a person’s appearance..
        '''</summary>
        Friend Shared ReadOnly Property q30() As String
            Get
                Return ResourceManager.GetString("q30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I know how to tell if someone listening to me is getting bored..
        '''</summary>
        Friend Shared ReadOnly Property q31() As String
            Get
                Return ResourceManager.GetString("q31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it easy to do more than one thing at once..
        '''</summary>
        Friend Shared ReadOnly Property q32() As String
            Get
                Return ResourceManager.GetString("q32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When I talk on the phone, I’m not sure when it’s my turn to speak..
        '''</summary>
        Friend Shared ReadOnly Property q33() As String
            Get
                Return ResourceManager.GetString("q33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I enjoy doing things spontaneously..
        '''</summary>
        Friend Shared ReadOnly Property q34() As String
            Get
                Return ResourceManager.GetString("q34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am often the last to understand the point of a joke..
        '''</summary>
        Friend Shared ReadOnly Property q35() As String
            Get
                Return ResourceManager.GetString("q35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it easy to work out what someone is thinking or feeling just by looking at their face..
        '''</summary>
        Friend Shared ReadOnly Property q36() As String
            Get
                Return ResourceManager.GetString("q36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If there is an interruption, I can switch back to what I was doing very quickly..
        '''</summary>
        Friend Shared ReadOnly Property q37() As String
            Get
                Return ResourceManager.GetString("q37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am good at social chitchat.
        '''</summary>
        Friend Shared ReadOnly Property q38() As String
            Get
                Return ResourceManager.GetString("q38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to People often tell me that I keep going on and on about the same thing..
        '''</summary>
        Friend Shared ReadOnly Property q39() As String
            Get
                Return ResourceManager.GetString("q39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I frequently get so strongly absorbed in one thing that I lose sight of other things..
        '''</summary>
        Friend Shared ReadOnly Property q4() As String
            Get
                Return ResourceManager.GetString("q4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When I was young, I used to enjoy playing games involving pretending with other children..
        '''</summary>
        Friend Shared ReadOnly Property q40() As String
            Get
                Return ResourceManager.GetString("q40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I like to collect information about categories of things (e.g., types of cars, birds, trains, plants)..
        '''</summary>
        Friend Shared ReadOnly Property q41() As String
            Get
                Return ResourceManager.GetString("q41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it difficult to imagine what it would be like to be someone else.
        '''</summary>
        Friend Shared ReadOnly Property q42() As String
            Get
                Return ResourceManager.GetString("q42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I like to carefully plan any activities I participate in..
        '''</summary>
        Friend Shared ReadOnly Property q43() As String
            Get
                Return ResourceManager.GetString("q43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I enjoy social occasions..
        '''</summary>
        Friend Shared ReadOnly Property q44() As String
            Get
                Return ResourceManager.GetString("q44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it difficult to work out people’s intentions..
        '''</summary>
        Friend Shared ReadOnly Property q45() As String
            Get
                Return ResourceManager.GetString("q45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New situations make me anxious..
        '''</summary>
        Friend Shared ReadOnly Property q46() As String
            Get
                Return ResourceManager.GetString("q46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I enjoy meeting new people..
        '''</summary>
        Friend Shared ReadOnly Property q47() As String
            Get
                Return ResourceManager.GetString("q47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am a good diplomat..
        '''</summary>
        Friend Shared ReadOnly Property q48() As String
            Get
                Return ResourceManager.GetString("q48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am not very good at remembering people’s date of birth..
        '''</summary>
        Friend Shared ReadOnly Property q49() As String
            Get
                Return ResourceManager.GetString("q49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I often notice small sounds when others do not..
        '''</summary>
        Friend Shared ReadOnly Property q5() As String
            Get
                Return ResourceManager.GetString("q5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I find it very easy to play games with children that involve pretending..
        '''</summary>
        Friend Shared ReadOnly Property q50() As String
            Get
                Return ResourceManager.GetString("q50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I usually notice car number plates or similar strings of information..
        '''</summary>
        Friend Shared ReadOnly Property q6() As String
            Get
                Return ResourceManager.GetString("q6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other people frequently tell me that what I’ve said is impolite, even though I think it is polite..
        '''</summary>
        Friend Shared ReadOnly Property q7() As String
            Get
                Return ResourceManager.GetString("q7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to When I’m reading a story, I can easily imagine what the characters might look like..
        '''</summary>
        Friend Shared ReadOnly Property q8() As String
            Get
                Return ResourceManager.GetString("q8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I am fascinated by dates..
        '''</summary>
        Friend Shared ReadOnly Property q9() As String
            Get
                Return ResourceManager.GetString("q9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to you are probably autistic - please, consult doctor.
        '''</summary>
        Friend Shared ReadOnly Property rAutism() As String
            Get
                Return ResourceManager.GetString("rAutism", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property resDlgNo() As String
            Get
                Return ResourceManager.GetString("resDlgNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property resDlgYes() As String
            Get
                Return ResourceManager.GetString("resDlgYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to points.
        '''</summary>
        Friend Shared ReadOnly Property rGotPoints() As String
            Get
                Return ResourceManager.GetString("rGotPoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to most probably, you are not autistic.
        '''</summary>
        Friend Shared ReadOnly Property rSpoko() As String
            Get
                Return ResourceManager.GetString("rSpoko", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You receive.
        '''</summary>
        Friend Shared ReadOnly Property rYouGot() As String
            Get
                Return ResourceManager.GetString("rYouGot", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
